name: Package Dependencies

on:
  workflow_dispatch:  # 允许手动触发
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'sell.js'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]  # 使用 Node.js 20.x 版本
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # 启用npm缓存
        
    - name: Install dependencies
      run: |
        npm config set registry https://registry.npmmirror.com
        npm install
        
    - name: Install sell.js specific dependencies
      run: |
        npm install @opensea/seaport-js @truffle/hdwallet-provider fs random dotenv
        
    - name: Package node_modules
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        zip -r node_modules.zip node_modules/
        echo "打包完成，创建压缩文件 node_modules.zip"
        
    - name: Upload node_modules artifact
      uses: actions/upload-artifact@v3
      with:
        name: node_modules
        path: node_modules.zip
        retention-days: 5  # 设置保留期限
        
    - name: Package Info
      run: |
        echo "依赖打包已完成"
        echo "您可以在 Actions 页面下载 node_modules.zip"
